### ISSUE TITLE
Create google account for the Geocoding Service[Geolocation]

### ISSUE THREAD

**Issue by Mike-droid** [Platzi-Master-C9/booking-ui#11]
# Summary

Since we're gonna need the [Geocoding Service](https://developers.google.com/maps/documentation/javascript/geocoding#Geocoding) and the [Google Cloud Console](https://console.cloud.google.com/project/_/apiui/apis/enabled) we're also gonna need a google account that's gonna be related to the project.

To do:
[] Create google account
[] Save password and share it only with the people who need to access to the Google console
[] Enable API
[] Make some tests to see that everything is working fine

**Comment by ferdsng** [comment]
I think we can create this email, same name as slack channel c9-geolocation-squad@gmail.com

Acceptance Criteria :white_check_mark:

- [ ] Create Google Account
- [ ] Enable and configure API
- [ ] Save password and share it with the squad
- [ ] Create an example of map using Google Maps API

**Comment by ferdsng** [comment]
Here is an example of a map using the Google Maps API https://gmaps-api-test.vercel.app/
