### ISSUE TITLE
[WIP] feat: create a slider for the images of places [Places]

### ISSUE THREAD

**Issue by carlosHGit** [Platzi-Master-C9/booking-ui#13]
## Summary 💡
AS user we can see for different images of a place 
WHEN we type a place and press enter or search 
THEN the user have a image card component with a slider of pictures an one or two bottons to move forward or backward

![image](https://user-images.githubusercontent.com/65434330/156707101-2aa9db03-0a6e-4b33-9bf7-7ee4b55134eb.png)

So we need to build a slider for show the pictures of the place,  that we fetch from the API

## Acceptance Criteria ✅

- [x] Create card component
- [x] Create slider component
- [x] Fill with fake data the Card and Slider components
- [x] Create functionality in both ways for slider
- [x] Create a default view for the slider if we don't have any image of the fetch
- [x] Deploy to view how the components looks like
- [x] Testing
- [ ] Integrate components with monorepo UI

**Comment by carlosHGit** [comment]
Hi!, 

@andresfgz and I are working in the issue #13 and here we have some progress on the tasks that we want to share.

We are temporarily working on another repository until we include the components to the monorepo:
https://github.com/carlosHGit/card-component-booking

We are also using vercel to deploy the components and be able to review them on the web:
https://card-component-booking.vercel.app/

WIP:  We continue working on how to test test the components and finally we are attentive to any feedback or comments

**Comment by carlosHGit** [comment]
Hi! Now the issue have testing and  all the features finished in this repo:
https://github.com/carlosHGit/card-component-booking

WIP: Yesterday issue #91  was resolved and the places package is already created in the monorepo, currently I have local problems in my (WSL2) and I have not been able to run it correctly in the monorepo.
I'm working to solve it and publish the full PR that ends the issue

**Comment by alexcamachogz** [comment]
This task is complete. Pending to integrate with monorepo UI.
