### ISSUE TITLE
feat: details become a host [places]

### ISSUE THREAD

**Issue by andresfgz** [Platzi-Master-C9/booking-ui#19]
## Summary ��
​
Create the form structure that will receive the information for accommodation registration that the new host will post.
​
## Acceptance Criteria ✅
- [x]  Create first screen with call-to-action button with legend “Become a host”
- [ ]  Confirm new host identity with official document
- [x]  Create button with legends “next” and “back”
- [x]  Create second screen for type of accommodation, with buttons to select the type of accommodation
- [x]  Create second screen for number of guests information
- [x]  Create screen for  amenity services
- [x]  create button with legend “finish”
- [x]  Final screen with a final message and invitation to follow next steps
- [x]  Create form for receiving accommodation pictures
- [ ] Testing

**Comment by JorgeTTor** [comment]
# Issue Tasks
​
 Hello, @JoaquinMX  and I  are currently working on testing, this is the progress we have made so far.
​
#Acceptance Criteria ✅


- [ ✅] Create first screen with call-to-action button with legend “Become a host”
 -[✅ ]  Confirm new host identity with official document
- [✅ ] Create button with legends “next” and “back”
- [✅ ] Create second screen for type of accommodation, with buttons to select the type of accommodation
- [✅ ] Create second screen for number of guests information
- [ ✅] Create screen for amenity services
- [✅ ] create button with legend “finish”
- [ ✅] Final screen with a final message and invitation to follow next steps
- [ ✅] Create form for receiving accommodation pictures
- [ ]  Testing
​
We are working on another repository, until we complete testing
​
