### ISSUE TITLE
chore: choose a CSS architecture metodology

### ISSUE THREAD

**Issue by ItsCrisDiaz** [Platzi-Master-C9/booking-ui#34]
## Summary

Define which of the suggested CSS architecture patterns we'll use for Booking System

## Acceptance criteria

- [x] Define the CSS paradigm we want to apply to this project (Functional, Semantic, a mix of both)
- [x] Define the CSS methodology we should use for this project (Atomic Design, OOCSS, SMACSS, BEM, CUBE CSS)
- [ ] Abstract what kind of design elements we can express as utility classes

**Comment by 701i** [comment]
Hi, there are some task that looks like these issues:
We can work together
https://github.com/Platzi-Master-C9/booking-ui/issues/4
https://github.com/Platzi-Master-C9/booking-ui/issues/45
