### ISSUE TITLE
feat: Layout the search results page. [Search Engine]

### ISSUE THREAD

**Issue by Cristhian-Medina** [Platzi-Master-C9/booking-ui#41]
### Summary

To display the results of the search for places of interest of the user we will use this view:

![search results](https://user-images.githubusercontent.com/41627755/157037212-cc27c8e0-3521-4801-8a5e-3f09c846929c.png)

### Acceptance Criteria:

- [x] Layout of the structure.
- [x] Service that obtains the list and the pagination of places.

**Comment by jlonuz** [comment]
I think that in this topic the development of the "price","type of accommodation" and "classification" ui components should be considered
