### ISSUE TITLE
chore: Monorepo root setup

### ISSUE THREAD

**Issue by emanuelalvaradog** [Platzi-Master-C9/booking-ui#6]
## Summary 💡
We have to setup the frontend `monorepo` using next.js and `lerna` so that each frontend team can start the UI development.

## Acceptance Criteria ✅:
- [ ] Create the monorepo configuration where the root configs must contain `prettier` and the `npmrc`.
- [ ] Created monorepo with each squad package including the shared lib.
- [ ] Monorepo root scripts run properly.
- [ ] Each monorepo package scripts run properly.

**Comment by taberoajorge** [comment]
### Step by step

Define each of the UI components to be attached with the following command 

`lerna create @booking-ui/[your-package-name]`.

### Example

`lerna create @booking-ui/search-engine`

`Output:`

```
lerna create @frontend-services/search-engine
lerna notice cli v3.22.1
lerna info versioning independent
package name: (@frontend-services/search-engine)
version: (1.0.0)
description: This is the default template that lerna configures.
keywords:
home page: (https://github.com/Platzi-Master-c9/frontend-services/tree/master/packages/search-engine#readme)
license: (ISC)
entry point: (lib/search-engine) lib/index.js
git repository: (https://github.com/Platzi-Master-C9/frontend-services.git) |
```

**Comment by taberoajorge** [comment]
@gh0stl1m  From a macro point of view, I think you have to set up local dependencies, and the libraries to be used to create the links.

**Comment by taberoajorge** [comment]
@elyager
