### ISSUE TITLE
[NOTIFICATIONS] Feat: create notifications module in booking UI

### ISSUE THREAD

**Issue by Basultobd** [Platzi-Master-C9/booking-ui#69]

**Comment by leolicona** [comment]
This issue has been resolved

**Comment by basultobdKs** [comment]
> This issue has been resolved

Please Leo add a description on what has been done, the objectives and a link to the PR or add comment in the PR doing a reference to this issue.

**Comment by leolicona** [comment]
I created the notifications sytems package into Booking UI folder and  I made this task using yarn and lerna.
